"""Changed WorkLog 

Revision ID: 5d52207edf51
Revises: 032553a7f454
Create Date: 2026-02-01 21:27:05.282482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d52207edf51'
down_revision: Union[str, Sequence[str], None] = '032553a7f454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worklog', sa.Column('total_duration_minutes', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worklog', 'total_duration_minutes')
    # ### end Alembic commands ###
