"""Removed adjustment model and schema

Revision ID: 5f6cd78b05a8
Revises: eb9d1c094022
Create Date: 2026-02-01 00:40:28.329280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6cd78b05a8'
down_revision: Union[str, Sequence[str], None] = 'eb9d1c094022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
