"""Removed adjustment model

Revision ID: abc4a8e46133
Revises: f009182f3dee
Create Date: 2026-02-01 00:24:47.041233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc4a8e46133'
down_revision: Union[str, Sequence[str], None] = 'f009182f3dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjustment_worklog_id'), table_name='adjustment')
    op.drop_table('adjustment')
    op.add_column('timesegment', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_timesegment_user_id'), 'timesegment', ['user_id'], unique=False)
    op.create_foreign_key(None, 'timesegment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timesegment', type_='foreignkey')
    op.drop_index(op.f('ix_timesegment_user_id'), table_name='timesegment')
    op.drop_column('timesegment', 'user_id')
    op.create_table('adjustment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('worklog_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], name=op.f('adjustment_worklog_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('adjustment_pkey'))
    )
    op.create_index(op.f('ix_adjustment_worklog_id'), 'adjustment', ['worklog_id'], unique=False)
    # ### end Alembic commands ###
